config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts
  mount RailsAdmin::Engine => '/setup', as: 'rails_admin'
  resources :achievements
  resources :projects
  resources :skills

  devise_for :admins, :skip => :registrations

  #Enabling to change password even telling to skip registrations
  as :admin do
    get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    patch 'admins' => 'devise/registrations#update', :as => 'admin_registration'
  end

  resources :hero_phrases
  resources :abouts
  root 'pages#home'
end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hero_phrase.rb
class HeroPhrase < ActiveRecord::Base
end

app/models/post.rb
require "html_truncator"

class Post < ApplicationRecord
	validates :title, :body, :presence => true


	def excerpt	
		puts HTML_Truncator.truncate(self.body.to_s.html_safe, 100)
	end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_attached_file :image, styles: { thumb: "404x250>" }, :default_url => "project_missing_:style.jpg"


  validates_attachment :image, presence: true,
                            content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                            size: { less_than: 1.megabytes }
end

app/models/skill.rb
class Skill < ActiveRecord::Base
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_about, only: [:show, :edit, :update, :destroy]

  # GET /abouts
  # GET /abouts.json
  def index
    @abouts = About.all
  end

  # GET /abouts/1
  # GET /abouts/1.json
  def show
  end

  # GET /abouts/new
  def new
    @about = About.new
  end

  # GET /abouts/1/edit
  def edit
  end

  # POST /abouts
  # POST /abouts.json
  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: 'About was successfully created.' }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { render :new }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abouts/1
  # PATCH/PUT /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.json
  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to abouts_url, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = About.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_params
      params.require(:about).permit(:title, :description, :order)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @about_items = About.order(:order)
    @skills = Skill.order(:order)
    @portfolio = Project.where(visible: true)
    @achievements = Achievement.order(when: :desc)

    #This will not load all the attributes. Will bring only the text attribute in an array.
    @phrases = HeroPhrase.pluck(:text)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:title, :description, :order)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hero_phrases_helper.rb
module HeroPhrasesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Julio Cesar Fausto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if admin_signed_in? %>
    <%= link_to 'Logout ('+current_admin.email+')', destroy_admin_session_path, method: :delete %>
    <%= link_to "Change your password", edit_admin_registration_path %>
  <% end %>

  <%= render 'layouts/messages' %>

  <%= yield %>

  <!-- Google Analytics -->
  <%= analytics_init if Rails.env.production? %>
</body>
</html>

app/views/pages/_about.html.erb
<a id="about"></a>
<%= react_component "AboutList", about_items: @about_items %>

app/views/pages/_achievements.html.erb
<a id="achievements"></a>
<%= react_component "AchievementList", achievements: @achievements %>

<!--
      <section>
        <h3><span>Some Achievements This Year</span></h3>
        <ul class="achievements">
          <li>
            <p>02 November 2015</p>
            <p>Lauched this website built with Rails <a href="http://jcfausto.com/" target="_blank">jcfausto.com</a></p>
          </li>
          <li>
            <p>20 September 2015</p>
            <p>Scored 7.0 at IELTs</p>
          </li>
          <li>
            <p>1 July 2015</p>
            <p>Launched an iPhone app for book readers called <a href="http://manypagesapp.com/" target="_blank">ManyPagesApp</a></p>
          </li>
          <li>
            <p>2 February 2015</p>
            <p>Certified as <a href="https://www.scaledagileframework.com/" target="_blank">SAFe Agilist (SA)</a></p>
          </li>
        </ul>
      </section-->

app/views/pages/_body.html.erb
<div class="page-body">

  <%= render 'pages/about' %>

  <div id="me">
    <img class="me">
  </div>

  <%= render 'pages/skills' %>

  <%= render 'pages/portfolio' %>

  <%= render 'pages/achievements' %>

  <%= render 'pages/latest_blog_articles' %>

  <a name="contact" id="contact"></a>

  <%= render 'pages/footer' %>

 </div>

app/views/pages/_footer.html.erb
   <footer>
        <hr>
        <p>Hosted on <a href="http://digitalocean.com/" target="_blank">Digital Ocean</a>.<br>
        Source Code Available on <a href="https://github.com/jcfausto" target="_blank">GitHub</a><br>
        Created with Rails and &hearts; by myself</p>
        <hr>
        <ul>
          <li><a href="https://plus.google.com/+JulioCesarFausto" title="Google+"><svg viewBox="0 0 80 80">
  <g fill="#fff">
    <ellipse stroke-width="4" cx="40" cy="40" rx="38" ry="38" />
    <path d="M60 39.4L55.6 39.4 55.6 35 53.4 35 53.4 39.4 49 39.4 49 41.6 53.4 41.6 53.4 46 55.6 46 55.6 41.6 60 41.6 60 39.4M37.2 57C32.2 57 29 54.7 29 51.4 29 48.2 32 47.1 33 46.7 34.9 46.1 37.5 46 37.9 46 38.3 46 38.6 46 38.9 46 42.5 48.5 44 49.7 44 52.1 44 54.9 41.6 57 37.2 57L37.2 57ZM36.7 39C32.8 39 31 33.9 31 30.9 31 29.7 31.2 28.3 32 27.4 32.7 26.5 34 26 35.2 26 39 26 41 31.1 41 34.4 41 35.2 40.9 36.6 39.9 37.6 39.1 38.3 37.9 39 36.7 39L36.7 39ZM43.9 43.9L42.2 42.6C41.7 42.2 41 41.6 41 40.6 41 39.6 41.7 39 42.3 38.4 44.3 36.9 46.3 35.3 46.3 31.9 46.3 28.4 44.1 26.7 43 25.8L45.9 25.8 49 24 39 24C36.4 24 32.9 24.3 30.1 26.4 28.1 28.1 27.4 30.6 27.4 32.7 27.4 36.3 30.3 39.9 35.4 39.9 35.9 39.9 36.4 39.9 36.9 39.8 36.7 40.4 36.4 40.8 36.4 41.6 36.4 43 37.2 43.9 37.9 44.7 35.7 44.9 31.7 45.1 28.7 46.8 25.9 48.4 25 50.8 25 52.4 25 55.8 28.2 59 35.2 59 43.5 59 48 54.6 48 50.3 48 47.1 46 45.6 43.9 43.9L43.9 43.9Z" />
  </g>
</svg>
</a></li>
          <li><a href="https://www.facebook.com/julio.c.fausto" title="Facebook"><svg viewBox="0 0 80 80">
  <g fill="#fff">
    <ellipse stroke-width="4" cx="40" cy="40" rx="38" ry="38" />
    <path d="M42.3 57L42.3 41 47.9 41 48.8 34.8 42.3 34.8 42.3 30.8C42.3 29 42.9 27.8 45.6 27.8L49 27.8 49 22.2C48.4 22.2 46.4 22 44 22 39 22 35.6 24.9 35.6 30.2L35.6 34.8 30 34.8 30 41 35.6 41 35.6 57 42.3 57" />
  </g>
</svg>
</a></li>
          <li><a href="https://twitter.com/jcfausto" title="Twitter"><svg viewBox="0 0 80 80">
  <g fill="#fff">
    <ellipse stroke-width="4" cx="40" cy="40" rx="38" ry="38" />
    <path d="M53.9 31.7C55.4 30.8 56.5 29.3 57 27.6 55.6 28.4 54.1 29.1 52.5 29.4 51.2 27.9 49.3 27 47.2 27 43.3 27 40.1 30.4 40.1 34.6 40.1 35.2 40.1 35.7 40.2 36.3 34.3 36 29 33 25.4 28.4 24.8 29.5 24.5 30.8 24.5 32.2 24.5 34.8 25.7 37.1 27.7 38.5 26.5 38.5 25.4 38.1 24.4 37.6 24.4 37.6 24.4 37.6 24.4 37.6 24.4 41.3 26.9 44.4 30.2 45.1 29.6 45.2 28.9 45.3 28.3 45.3 27.8 45.3 27.4 45.3 26.9 45.2 27.8 48.2 30.5 50.4 33.6 50.5 31.2 52.5 28.1 53.7 24.7 53.7 24.1 53.7 23.6 53.7 23 53.6 26.2 55.7 30 57 34 57 47.2 57 54.4 45.5 54.4 35.5 54.4 35.1 54.4 34.8 54.4 34.5 55.8 33.4 57 32.1 58 30.6 56.7 31.2 55.3 31.6 53.9 31.7Z" />
  </g>
</svg>
</a></li>
          <li><a href="https://github.com/jcfausto" title="GitHub"><svg viewBox="0 0 80 80">
  <g fill="#fff">
    <ellipse stroke-width="4" cx="40" cy="40" rx="38" ry="38" />
    <path d="M29 47.5C29.7 48.1 30.1 48.8 30.1 48.8 30.1 48.9 30.2 48.9 30.2 49L30.2 49C30.2 49 30.2 49 30.1 49 30 49.2 30 49.5 30.1 49.7 30.3 50 30.7 50.1 30.9 50 30.9 49.9 30.9 49.9 30.9 49.9 32.5 51.3 34.4 50.7 35.2 50.3 35.4 49.1 35.8 48.3 36.3 47.9 32.4 47.4 28.3 45.9 28.3 39 28.3 37 29 35.4 30.1 34.2 30 33.7 29.4 31.9 30.3 29.4 30.3 29.4 31.8 29 35.1 31.3 36.5 30.9 38 30.7 39.5 30.7 41 30.7 42.5 30.9 43.9 31.3 47.2 29 48.7 29.4 48.7 29.4 49.6 31.9 49 33.7 48.9 34.2 50 35.4 50.7 37 50.7 39 50.7 45.9 46.6 47.4 42.7 47.9 43.3 48.4 43.9 49.5 43.9 51.2 43.9 53.6 43.8 55.5 43.8 56.1 43.8 56.6 44.2 57.1 45 57 52 54.6 57 47.9 57 39.9 57 30 49.2 22 39.5 22 29.8 22 22 30 22 39.9 22 47.9 27 54.6 34 57 34.8 57.1 35.2 56.6 35.2 56.1 35.2 55.7 35.1 54.3 35.1 52.8 30.3 53.9 29.2 50.6 29.2 50.6 28.4 48.6 27.3 48 27.3 48 25.7 46.9 27.4 46.9 27.4 46.9 27.7 47 27.9 47 28.1 47.1 28.1 47.1 28 47.2 28 47.2 27.9 47.5 28.1 47.8 28.4 47.9 28.6 48.1 28.9 48 29 47.8 29 47.7 29 47.6 29 47.5ZM28.9 48.9C28.7 49.1 28.4 49 28.2 48.8 28 48.5 27.9 48.2 28.1 48.1 28.3 47.9 28.6 48 28.8 48.2 29 48.5 29.1 48.8 28.9 48.9ZM30.9 51.9C30.8 52.1 30.5 52 30.2 51.8 30 51.6 29.9 51.3 30.1 51.1 30.2 50.9 30.5 51 30.8 51.2 31 51.4 31.1 51.7 30.9 51.9ZM33 51.7C32.9 52 32.7 52.1 32.4 52 32.1 51.8 32 51.6 32 51.3 32.1 51 32.3 50.9 32.6 51 32.9 51.2 33 51.4 33 51.7ZM34 51.5C34 51.8 33.8 52 33.5 52 33.2 52 33 51.8 33 51.5 33 51.2 33.2 51 33.5 51 33.8 51 34 51.2 34 51.5ZM35 51.4C35 51.6 34.8 51.9 34.6 52 34.3 52.1 34 51.9 34 51.6 34 51.4 34.2 51.1 34.4 51 34.7 50.9 35 51.1 35 51.4Z" />
  </g>
</svg>
</a></li>
          <li><a href="https://www.linkedin.com/in/jcfausto" title="LinkedIn"><svg viewBox="0 0 80 80">
  <g fill="#fff">
    <ellipse stroke-width="4" cx="40" cy="40" rx="38" ry="38" />
    <g transform="translate(23, 22)" fill="#000">
      <path d="M4.6 0.6C6.7 0.6 8.5 2.4 8.5 4.6 8.5 6.8 6.7 8.5 4.6 8.5 2.4 8.5 0.6 6.8 0.6 4.6 0.6 2.4 2.4 0.6 4.6 0.6L4.6 0.6ZM1.2 11.5L8 11.5 8 33.4 1.2 33.4 1.2 11.5ZM12.2 11.5L18.7 11.5 18.7 14.5 18.8 14.5C19.7 12.8 21.9 11 25.2 11 32.1 11 33.4 15.5 33.4 21.4L33.4 33.4 26.6 33.4 26.6 22.7C26.6 20.2 26.5 16.9 23.1 16.9 19.5 16.9 19 19.7 19 22.5L19 33.4 12.2 33.4 12.2 11.5" />
    </g>
  </g>
</svg>
</a></li>
          <li><a href="mailto:hello@jcfausto.com" title="Email"><svg viewBox="0 0 80 80">
  <g fill="#fff">
    <ellipse stroke-width="4" cx="40" cy="40" rx="38" ry="38" />
    <path d="M45 40.4L58 50 58 28 45 40.4 45 40.4ZM23 28L23 50 36 40.4 23 28 23 28ZM40.5 45.2L37.5 42 23 52 58 52 43.5 42 40.5 45.2 40.5 45.2ZM57 28L24 28 40.5 42 57 28 57 28Z" />
  </g>
</svg>
</a></li>
        </ul>
      </footer>

app/views/pages/_header.html.erb
    <div class="page-header"><a name="home" id="home"></a>
      <header><a href="/" class="logo">JCF</a>
        <div class="popup-nav"><a class="trigger"><span></span></a>
          <nav>
            <ul>
              <li><a href="#home" data-scroll>Home</a></li>
              <li><a href="#about" data-scroll>About</a></li>
              <li><a href="#skills" data-scroll>Skills</a></li>
              <li><a href="#portfolio" data-scroll>Portfolio</a></li>
              <li><a href="#achievements" data-scroll>Achievements</a></li>
              <li><a href="#blog" data-scroll>Blog</a></li>
              <li><a href="#contact" data-scroll>Contact</a></li>
              <li><a target="_blank" href="#">Résumé</a></li>
            </ul>
          </nav>
        </div>
        <nav>
          <ul>
            <li><a href="#home" data-scroll>Home</a></li>
            <li><a href="#about" data-scroll>About</a></li>
            <li><a href="#skills" data-scroll>Skills</a></li>
            <li><a href="#portfolio" data-scroll>Portfolio</a></li>
            <li><a href="#achievements" data-scroll>Achievements</a></li>
            <li><a href="#blog" data-scroll>Blog</a></li>
            <li><a href="#contact" data-scroll>Contact</a></li>
            <li><a target="_blank" href="#">Résumé</a></li>
          </ul>
        </nav>
      </header>
      <div class="hero">
        <h2>WELCOME TO MY WEBSITE</h2>
        <h1>JULIO CESAR FAUSTO</h1>
        <h2><%= react_component "PhraseShuffler", phrases: @phrases.to_a %></h2>
      </div>

      <div class="scroll">
        <p><a href="#about" data-scroll>FIND OUT MORE</a></p><a href="#about" data-scroll><svg viewbox="0 0 30 30">
  <g fill="#FFF">
    <path d="M25.5 11L25.5 12 4.5 12 4.5 10 23.5 10 23.5-9 25.5-9 25.5 11Z" transform="translate(15.049242, 1.5) rotate(45) translate(-15.049242, -1.5)" />
    <path d="M25.5 24.3L25.5 25.3 4.5 25.3 4.5 23.3 23.5 23.3 23.5 4.3 25.5 4.3 25.5 24.3Z" transform="translate(15.049242, 14.849242) rotate(45) translate(-15.049242, -14.849242)" />
  </g>
</svg>
</a>
      </div>
    </div>

app/views/pages/_latest_blog_articles.html.erb
      <a id="blog"></a>
      <section class="inverted">
        <h3><span>Recent Blog Posts</span></h3>
        <ul class="posts">
          <li>
            <p>24 June 2015 on iOS Development</p>
            <p><a href="http://ludworks.com/easypress/manypages-how-i-built-my-first-iphone-app/">ManyPages – How I Built My First iPhone App</a></p>
          </li>
          <li>
            <p>10 March 2015 on Mobile Desing, Photoshop, UI</p>
            <p><a href="http://ludworks.com/easypress/my-health-app-ios-8-mobile-user-interface-design/">My Health App – iOS 8 Mobile User Interface Design</a></p>
          </li>
          <li>
            <p>4 March 2015 on Mobile Design, Photoshop, UI</p>
            <p><a href="http://ludworks.com/easypress/recreating-the-udemy-mobile-ux-while-learning-photoshop-and-ux-prototyping/">Recreating The Udemy Mobile UI While Learning Photoshop and UI Prototyping</a></p>
          </li>
        </ul>
      </section>

app/views/pages/_portfolio.html.erb
<a id="portfolio"></a>
<%= react_component "Portfolio", portfolio_items: @portfolio %>

app/views/pages/_skills.html.erb
<a id="skills"></a>
<%= react_component "SkillList", skill_items: @skills %>

app/views/pages/home.html.erb
<%= render 'pages/header' %>

<%= render 'pages/body' %>

<%= javascript_include_tag 'scripts' %>